#!/bin/sh
#
# "$Id$"
#
#   Psuedo-backend for CUPS testing purposes.
#
#   Copyright 2011 by Apple Inc.
#
#   These coded instructions, statements, and computer programs are the
#   property of Apple Inc. and are protected by Federal copyright
#   law.  Distribution and use rights are outlined in the file "LICENSE.txt"
#   which should have been included with this file.  If this file is
#   file is missing or damaged, see the license at "http://www.cups.org/".
#
#   This file is subject to the Apple OS-Developed Software exception.
#

if test $# = 0; then
	echo 'direct pseudo:///deskjet "HP DeskJet" "HP DeskJet (pseudo)" "MFG:HP;MDL:DeskJet;CMD:PCL;" "Nowhere"'
	echo 'direct pseudo:///laserjet "HP LaserJet" "HP LaserJet (pseudo)" "MFG:HP;MDL:LaserJet;CMD:PCL;" "Nowhere"'
    echo 'direct usb://Samsung/CLP-360%20Series?serial=CN2AVBXGBY05KC "Samsung CLP-360 Series" "Samsung CLP-360 Series" "MFG:Samsung;MDL:CLP-360 Series;CMD:SPL;" "Nowhere"'
    echo 'direct usb://Samsung/CLX-3160%20Series?serial=CN2AVBX "Samsung CLX-3160 Series" "Samsung CLX-3160 Series" "MFG:Samsung;MDL:CLX-3160 Series;CMD:SPL;" "Nowhere"'
    echo 'direct usb://Samsung/SCX-4x21%20Series?serial=CN2AVBXGBYC "Samsung SCX-4x21 Series" "Samsung SCX-4x21 Series" "MFG:Samsung;MDL:SCX-4x21 Series;CMD:SPL;" "Nowhere"'
    echo 'direct usb://Samsung/ML-371x%20Series?serial=CN2AVBXGB "Samsung ML-371x Series" "Samsung ML-371x Series" "MFG:Samsung;MDL:ML-371x Series;CMD:SPL;" "Nowhere"'
	exit 0
fi

cat $6 >/dev/null
sleep 5
exit 0

#
# End of "$Id$".
#
